### PR TITLE
Coolant based ASE %, ASE duration, priming pulse width and Coolant based ignition adjustment

### PR DESCRIPTION
**Pull request by pazi88**
Speeduino was lacking coolant based After Start Enrichment, After Start Enrichment duration and Priming pulse widths. Which are mandatory features when using car in cold environments. Also the ignition timing needs to be adjusted based on coolant temperature in cold environments to maintain engine performance also with cold engine. So that feature is also added as Cold Advance.

### CODE REVIEW

**Comment by VitorBoss** [comment]
The table lookup could be perform just once a second if you add a variable and put lookup on speeduino.ino#L279, temperatures don't spikes on a second IMAO.

Good job.

**Comment by pazi88** [comment]
@VitorBoss Yes you are right, but I wanted to make this simple as possible, without doing too many changes.

I have now tested all these changes so that they actually work. The third commit is because I needed to fix the priming pulse width.

**Comment by noisymime** [comment]
I think there's an improvement to be made here with the coolant read on startup. I suspect you're probably not getting an accurate value due to it being the first read. The filter will be (or could be) dramatically distorting the true read. I'll add an option on the coolant sensor read to bypass the filter if desired.

**Comment by pazi88** [comment]
Oh you are right. I didn't think about that. I tested this on my tune where I have filters set to 0, because that gives me stable readings in my setup. So the filters didn't distort readings. And yeah bypassing the filter for this would work fine, becsuse it doesn't matter if the reading would few degrees off, because possible noise.

**Comment by lsdlsd88** [comment]
is it me or the new ASE dialogs need some GUI tweaks? here you can see the FONT SIZE is very different from the usual. adding default values in the base tune would also be more user friendly.

ase

**Comment by pazi88** [comment]
The TS is very strange about that. The fonts looked strange on my PC also but I didn't find anywhere to adjust those. Not even after hours of trying to figure that out. But then after populating tables with sensible values, saving tune and closing the TS. The fonts were ok next time I opened TS. And yes some default values would be ok. I think josh already made change that for old tunes, the old ASE, priming etc values are used to populate those curves when updating FW version.

**Pull request merged**
