### PR TITLE
Add layout for SCG_ECU V1.0

### PR DESCRIPTION
**Pull request by sbtoonz**
None of the layouts outlined in DVJCodecs thread work for his PCB Design

I have made the proper changes in order for this board to be chosen from tunerstudio from here forward

### CODE REVIEW

**Comment by noisymime** [comment]
@dvjcodec - Are you able to confirm the requirement here? Is this pin layout in addition to the Rev A and Rev B mappings that are already present or should these values replace one of the existing ones?

**Comment by sbtoonz** [comment]
RevA pinout does not match his board 
RevB Pinout does not match his board

Neither are setup to use all 8 outputs of his board design

**Comment by subzero2379** [comment]
Ignition outpout 1 and 2 no works with latest firmware,second question how you activate lc1 outpout

**Comment by sbtoonz** [comment]
@subzero2379  the Ignition output 1/2 broke again shortly after patch 33485ae9e11e4c3e845ba123244dd24b0a1d6b20 was applied. 

I had success just commenting out the CANbus pin startup as I dont even need them for my application. 

the bug is something persistent from the Teensy CANbus source code itself and @noisymime  has filed a bug report with them in hopes to resolve I believe


https://github.com/noisymime/speeduino/commit/33485ae9e11e4c3e845ba123244dd24b0a1d6b20#diff-6f227b44a2d579abd2988cee4bfabc30186f04c7724a51c422a0f28be708fffaR234


Could also try updating the Flexcan library to a newer version
https://github.com/pawelsky/FlexCAN_Library

**Comment by subzero2379** [comment]
i set up pin (def): ti pin(3); and pin(4); and compileok the fw 
i dont need can bus i want to disable.after  make changes 
ign 1,2 work ok on latest fw.
but i had to edit pin manually and remap to ecu teen rev b

**Comment by sbtoonz** [comment]
> i set up pin (def): ti pin(3); and pin(4); and compileok the fw
> i dont need can bus i want to disable.after make changes
> ign 1,2 work ok on latest fw.
> but i had to edit pin manually and remap to ecu teen rev b

Can you share the mapping you did in a comment here so I can test on my setup and rebase my pull request so the board works as expected

**Comment by subzero2379** [comment]
//Note: This must come after the call to setPinMapping() or else pins 29 and 30 will become unusable as outputs. Workaround for: https://github.com/tonton81/FlexCAN_T4/issues/14
#if defined(CORE_TEENSY35)
  Can0.setRX(3);
  Can0.setTX(4);
#endif

**Comment by marteen71** [comment]
this solved my  issue with Pin 29, 30 which i use in Speeduino as IGN1, 2.  becouse DEF = 1 and ALT = 0 and  0 defines pin 3,4 for the CANBus. 

 #if defined (NATIVE_CAN_AVAILABLE)
      configPage9.intcan_available = 1;   // device has internal canbus
      //Teensy uses the Flexcan_T4 library to use the internal canbus
      //enable local can interface
      //setup can interface to 500k   
      Can0.begin();
      Can0.setBaudRate(500000);
      Can0.enableFIFO();
    #endif

    #if defined(CORE_TEENSY35)
      Can0.setRX(ALT);
      Can0.setTX(ALT);
    #endif

**Pull request closed without merging**
