### PR TITLE
Water methanol injection

### PR DESCRIPTION
**Pull request by Timu5**
This pr fulfill feature request #154.
Implementation is based on description from forum post [Water / Meth injection - $200 bounty](https://speeduino.com/forum/viewtopic.php?p=43797#p43797).

WMI utilize VVT timer, therefor only one can work at any given time.  When WMI is enabled and WMI alternative boost map is on, the VVT table is being used as current boost map.

### CODE REVIEW

**Comment by noisymime** [comment]
Terrific PR! 

Most of this looks fine and I'm more than happy to pull in, I do have  few questions though:

1. What is happening with the vvt as boost stuff that's in there? Is this critical to the WMI work or can it be split out?
2. The current dev data version (In `updates.ino`) is 14, so no need to add a version 15
3. There's a few bugs in some of the boost code that's been changed

I'll go through and add comments and changes directly on the PR if you're OK with it.

**Comment by Timu5** [comment]
1. Nope, it not critical, is just idea to reuse vvt table as alternative boost table to save some memory, it can be safely moved to its own map. Alternative boost map is allowing to use higher boost when water injection is operational(cooling effect of water on intake manifold).
2. Didn't know that. I will change it in free time.
3. Hmm, that's weird because its only selecting which map to use, and was working just fine when tested. Maybe I'm missing something, more details would be useful.

> I'll go through and add comments and changes directly on the PR if you're OK with it.

That's fine.

**Comment by noisymime** [comment]
Can I ask that the vvt as boost table stuff be pulled out for this PR? Once the work is done to complete the memory consolidation, I had planned on adding a 2nd boost table anyway, so that feature will still be there. I just feel it's going to create too much confusion having a joint table like that is all.

**Comment by Timu5** [comment]
I removed vvt as boost and change data version back to 14.

**Comment by noisymime** [comment]
Terrific work! Thanks for the PR

**Pull request merged**
