### PR TITLE
Lower max on IAT and CLT gauges for celsius

### PR DESCRIPTION
**Pull request by DeionSi**
Lowers the maximum for Celsius on the IAT and CLT gauges in TunerStudio to a more reasonable value.

### CODE REVIEW

**Comment by DeionSi** [comment]
(and fuel temp)

**Comment by jonbills** [comment]
I think 110 is too low for CLT on some modern cars, e. g. I had a mini where the fan didn't cut in until 115.

**Comment by DeionSi** [comment]
It seems some Minis have 112c for the high fan. Change both Celsius and Fahrenheit to max 120c/248f.

**Comment by brunob45** [comment]
Make it configurable in TS like the rpm gauge?

**Comment by noisymime** [comment]
> Make it configurable in TS like the rpm gauge?

I think this would be a good addition if anyone feels like adding the local setting. For now I'll pull this in though as it is an improvement over what's there.

**Pull request merged**
