### PR TITLE
[ASE] Transition time to disable

### PR DESCRIPTION
**Pull request by VitorBoss**
Configurable time in 0.1S resolution

### CODE REVIEW

**Comment by muuris** [comment]
Great addition! Especially when the ASE needs to have a big value, without this fade off-transition the engine easily either coughs/runs rough, or runs unnecessarily rich for longer than needed.

**Comment by VitorBoss** [comment]
ASE

**Comment by noisymime** [comment]
You've setup a configuration variable `ASEValue` but then appear to be using this to track a status value. `ASEValue` should be on `currentStatus` rather than as a map variable as it's not part of the tune itself.

**Comment by noisymime** [comment]
Also:
`volatile int runSecsX10;`

Should be a uint16_t. You're checking for it to overflow at 65535, but have declared it as a signed int (Which will overflow at half that)

**Comment by VitorBoss** [comment]
Hope didn't miss what you mean with this commit

**Pull request merged**
