### PR TITLE
Sandman w ajeep patch 1

### PR DESCRIPTION
**Pull request by sandmanWAjeep**
I found an issue with the speeduino.ini file with the programmable outputs. The second condition of Rule number 1 would be applied to the second condition of rule number 2. I opened issue #464 about this. The fix is shown in the atached jpeg. This is the first time i've used the "Submit Issue" or "Pull Request" so hopefully i'm going about it the right way.

bugFix

### CODE REVIEW

**Comment by muuris** [comment]
It seems you found an issue and on a quick glance a fix for it too, but the pull request is a bit of a mess (see "files changed" and I believe you'll find there a bit more than intended to be included ;) ).

Your fork master should be equal with the master branch to start with (no personal mods or older version etc), then make a branch with a title and short description of the thing it changes (not "patch 1", but more like "fix programmable output 1 & 2 conditions") and only make the modifications inteded, then make a PR. When done like this, it's easy for everyone to see what were the changes -- not with a jpeg image but from the files changed. You can also compare your branch to master before making a PR.

**Comment by VitorBoss** [comment]
What you are proposing is move the TS addresses for the conditions, that won't work, I had wrote it and tested it for 2 months before submitting the pull request, on my tests everything was working as intended, I didn't test the Aux input thing, maybe is something related to that.

**Comment by sandmanWAjeep** [comment]
@muuris. 
Thank you for the information on correct pull request workflow. I made another pull request with only change being the bugfix for the programmable outputs. 

@VitorBoss
It is very possible that I'm wrong on this. But comparing the TS addresses associated with firstDataIn to those of secondData in, the addresses of secondDataIn are one digit off. This is exactly what i am seeing in tuner studio. If I had rule one set to "anyValue"  AND TPS ==0            and set rule two to            "anyTrueValue  AND  anyValue > 1,
rule two would go true any time the TPS was > 1

**Comment by VitorBoss** [comment]
Just had a second look on that and you are absolutely right, somewhere during the changes it got messed up, the condition0 must have the same address of the contrition array

**Pull request closed without merging**
