### PR TITLE
Global injector close angle

### PR DESCRIPTION
**Pull request by ConnerMcLaughlin**
This makes it easier to set the injector close angle with one setting instead of four.

### CODE REVIEW

**Comment by ConnerMcLaughlin** [comment]
Pull me code

**Comment by ConnerMcLaughlin** [comment]
Maybe I don't know enough about github but seeing commits after a PR seems like the code isn't going to be pulled.  I was hoping to get comments at least.

**Comment by noisymime** [comment]
Just a heads up, I will look to merge this early in Jan after the Dec release goes out. This will give me a little more time to test that there's no issues etc.

**Comment by ConnerMcLaughlin** [comment]
Don't stress too much over it.  In the firmware code(not TS) there is literally two lines of code!  But of course it's a deviation from the feature requests.  I always value your feedback.  Go Speeduinees!

**Comment by ConnerMcLaughlin** [comment]
January Bump

**Pull request merged**
