### PR TITLE
STM32F407 fixes

### PR DESCRIPTION
**Pull request by iLeeeZi**
These should fix 32bit timers missing/double pulses and SRAM backup write/read problems. Some board configurations did break because of the bluepill/blackpill "hacks" so those are now checked only with bluepill/blackpill boards.

### CODE REVIEW

**Comment by VitorBoss** [comment]
Speeduino code uses timers in microseconds format, tick is timer source clock, the overflow value should be kept same on all timers to scale. Allowable values for overflow are any value from 0 to max

**Comment by pazi88** [comment]
@VitorBoss problem is that with current implementation the injector and ignition pulses are randomly missing or too short and the stm32 is useless to control engine because of that. This PR fixes the random problems in inj/ign pulses.

**Comment by iLeeeZi** [comment]
And it looks like this: timer3

There is something weird with it and I agree that my "fix" might not be the correct method but at least it works fine with it. This only happens with the 32 bit counter timers.

**Comment by VitorBoss** [comment]
This problem is only on official core, on STM32GENERIC is just fine. I've forgot, the microseconds is set later when the timer clock is divided, the clock should be TICK, could you test with 16 bits please? Os STM32GENERIC is all 16bit and works just fine.

This misconception about timer mode is because HardwareTimer is different from the STM32GENERIC. Nice catch

**Comment by iLeeeZi** [comment]
Yeah I forgot to add that these fixes are only for the official core. I tested with 16bit max overflow but it is same as in the screenshot above. HardwareTimer library says that it handles all timers as 16bit but there seems to be some differences.

**Comment by VitorBoss** [comment]
The PWM pins output double of configured frequency, is just a copy-paste error, could you fix that by changing board_stm32_official.ino#L75 from 
`Timer1.setPrescaleFactor(((Timer1.getTimerClkFreq()/1000000) * 4)-1);   //4us resolution`
To
`Timer1.setPrescaleFactor(((Timer1.getTimerClkFreq()/1000000) * 2)-1);   //2us resolution`
Thanks

**Comment by iLeeeZi** [comment]
Of course! Is there any benefits or disadvantages if injection and ignition timers are also changed to the 2us resolution?

**Comment by VitorBoss** [comment]
With 2uS you get only a better accuracy, but for that change you have to change the `MAX_TIMER_PERIOD` and `uS_TO_TIMER_COMPARE(uS)` to match STM32GENERIC definitions

**Comment by iLeeeZi** [comment]
Thanks! Changed those too.

**Comment by Tjeerdie** [comment]
Hi ILeeeZi

I fixed those double pulse problems a couple of months ago on my black STM32F407VE boards. I tested the timing extensively with some digital analyzer and found to be correct. I will try find out what changed between my last commit and this to break the code.

I have some issues with this commit

1. It assumes timer 2 is always a 32 bit timer. This does not hold for every STM32F4 board I assume? Also did you check the result with this? As the overflow setting of 0xFFFF for a 32 bit or 16 bit timer should be equally correct. (If the timers are configured to reset to zero on overflow as this is supposed to happen)

I think there is another issue but i am not totally sure. The code assumes that the overflow always happens at 0XFFFF for every timer (16 bit). If the pulse end is set to a point that is over 0xFFFF it will subtract 0xFFFF from that number. example:
1. Pulse end wil be calculated to happen at 100us from now in code.  
2. Timer counter is now at 0X65500 
3. Pulse end interrupt is now set at  65500 + 100/2(usperpulse) = 65550 
4. Code will put pulse end at 65550 - 65535 = 15us (assuming 16 bit timers)
5. This will break pulses around the overflow (when start is before overflow and end after overflow) when timers overflow of 32bit timers is set at 0XFFFFFFFF 

I found this problem when using larger pulse widths and then the problem happens more frequently. Or is this problem mitigated in some other way?

**Comment by Tjeerdie** [comment]
> ~Speeduino code uses timers in microseconds format,~ tick is timer source clock, the overflow value should be kept same on all timers to scale. Allowable values for overflow are any value from 0 to max

overflow in the official core is not set in register format (bits) it is set in useconds. Therefore not set to 0XFFFF but to max timer periode in us. I know it is strange and it took me quite a while to figure out why the double pulses occurred.

**Comment by Tjeerdie** [comment]
> Of course! Is there any benefits or disadvantages if injection and ignition timers are also changed to the 2us resolution?

There is very nasty down side of the 2uS resolution. That will stick its ugly head up with very low RPM values. (slow running motors). Because there can never be a ign or inj pulse start scheduled longer than 0XFFFF*2 Us in advance. This can give trouble if during cranking to running the RPM < 457.77.

With 4uS resolution this trouble only starts with RPM < 228.88. And is therefore much more realistic number. 

So please do not change. There have been people with WV boxer motors that had trouble with this i think.

**Comment by iLeeeZi** [comment]
Thanks for looking for the issues! I will revert those changes and check if I get it working.

**Comment by iLeeeZi** [comment]
@Tjeerdie I did try your suggestions but double/missing pulses still happens on the TIM2 and TIM5. It seems to happen at every 65535us * timer resolution so with 4us resolution it happens at every 262140us. It is similar what you described about the 2us resolution downside but it is only happening on the 32 bit timers regardless of the RPM.

**Comment by Tjeerdie** [comment]
> @Tjeerdie I did try your suggestions but double/missing pulses still happens on the TIM2 and TIM5. It seems to happen at every 65535us * timer resolution so with 4us resolution it happens at every 262140us. It is similar what you described about the 2us resolution downside but it is only happening on the 32 bit timers regardless of the RPM.

Ok, i will try and investigate this weekend, I should have the time now with all the social distancing going on :-D. 

Maybe i "fixed" this problem a couple of months ago by just not using any 32 bit timers and not making an PR for this. I do remember seeing the same thing but i cannot remember how and when i fixed it. I will take a look at my personal repository to see what i did try around that time.  

Setting the overflow to 32 bits (or 0xFFFFFFF in registers) should not work at all i assumed. The pulse scheduler expects an overflow on 16 bits. I do not understand what is going on and why it even works kind of with the over flow set to 65535us on 16 bit timers. And not on 32 bit timers.

**Comment by Tjeerdie** [comment]
I only now see you changed the setOverflow type to TICK_FORMAT! Sorry man my mistake to overlook this. This is/should also be correct! Can you try one last thing? Setting ALL timers (also the 32bit timers TIM2 and TIM5) with:

TimerX.setOverflow(0xFFFF, TICK_FORMAT);

That should fix the double pulses on both 32bit and 16bit timers

**Comment by Tjeerdie** [comment]
Hi all

Some small update on this.

TimerX.setOverflow(0xFFFF, TICK_FORMAT); works for 16 bit timers not for 32 bit timers
TimerX.setOverflow(MAX_TIMER_PERIOD, MICROSEC_FORMAT); works for 16 bit timers not for 32 bit timers

TimerX.setOverflow(0xFFFFFFF, TICK_FORMAT); Does not solve the problem for 32 bit timers. There are no more pulses on the channels for that timer because scheduler does not work. 

I have the impression that callbacks for channel 1..4 are also called on overflow for 32 bit timers. I have no clue why yet. Still investigating.

**Comment by iLeeeZi** [comment]
Thanks for the update! I did check and the bug indeed seems to happen even with 0xFFFFFFF and it propably still happens with the 0xFFFFFFFF as you said so it just hides the issue.

**Comment by Tjeerdie** [comment]
> Thanks for the update! I did check and the bug indeed seems to happen even with 0xFFFFFFF and it propably still happens with the 0xFFFFFFFF as you said so it just hides the issue.

Just re-read my previous post. I edited it some more. It is all correct but i did not understand why in the beginning, now i finally do.

**Comment by iLeeeZi** [comment]
@Tjeerdie I appreciate your taking the time to check what really caused the problem. That explanation was good.

Looks like whole STM32F4 series has 32 bit TIM2 and TIM5 so I added a check for that and changed all timers back to 4us resolution. Later those could be changed to whatever works the best but for now I feel it is good enough.

**Pull request merged**
