### PR TITLE
Performance: 15%+ loop/sec speedup by optimising 3d table bilinear interpolation

### LINKED ISSUE #516: get3DTableValue() - inconsistent bin (axis) checking.
When searching for the Y axis bins, get3DTableValue() uses inconsistent criteria. I pulled together the various lines of code to illustrate, below.

X axis bin testing raw code:
```
    if ( (X <= fromTable->axisX[fromTable->lastXMax]) && (X > fromTable->axisX[fromTable->lastXMin]) )
    else if ( ((fromTable->lastXMax + 1) < fromTable->xSize ) && (X <= fromTable->axisX[fromTable->lastXMax +1 ]) && (X > fromTable->axisX[fromTable->lastXMin + 1]) ) //First make sure we're not already at the last X bin
    else if ( (fromTable->lastXMin > 0 ) && (X <= fromTable->axisX[fromTable->lastXMax - 1]) && (X > fromTable->axisX[fromTable->lastXMin - 1]) ) //First make sure we're not already at the first X bin
    if ( (X <= fromTable->axisX[x]) && (X > fromTable->axisX[x-1]) )
```

X axis bin testing statements simplified & normalized for clarity:
```
if ( (X > fromTable->axisX[fromTable->lastXMin])     &&  (X <= fromTable->axisX[fromTable->lastXMax]))
if ( (X > fromTable->axisX[fromTable->lastXMin + 1]) &&  (X <= fromTable->axisX[fromTable->lastXMax + 1]))
if ( (X > fromTable->axisX[fromTable->lastXMin - 1]) &&  (X <= fromTable->axisX[fromTable->lastXMax - 1]))
if ( (X > fromTable->axisX[x-1])                     &&  (X <= fromTable->axisX[x]))
```
Consistently checks `min < X <= max` :-)
	
Y axis bin testing raw code:
```
    if ( (Y >= fromTable->axisY[fromTable->lastYMax]) && (Y < fromTable->axisY[fromTable->lastYMin]) )
    else if ( (fromTable->lastYMin > 0 ) && (Y <= fromTable->axisY[fromTable->lastYMin - 1 ]) && (Y > fromTable->axisY[fromTable->lastYMax - 1]) ) //First make sure we're not already at the top Y bin
    else if ( ((fromTable->lastYMax + 1) < fromTable->ySize) && (Y <= fromTable->axisY[fromTable->lastYMin + 1]) && (Y > fromTable->axisY[fromTable->lastYMax + 1]) ) //First make sure we're not already at the bottom Y bin
    if ( (Y >= fromTable->axisY[y]) && (Y < fromTable->axisY[y-1]) )

```	
Y axis bin testing statements simplified & normalized for clarity:
```
    if ( (Y <  fromTable->axisY[fromTable->lastYMin])     && (Y >= fromTable->axisY[fromTable->lastYMax]))
    if ( (Y <= fromTable->axisY[fromTable->lastYMin - 1]) && (Y >  fromTable->axisY[fromTable->lastYMax - 1]) )
    if ( (Y <= fromTable->axisY[fromTable->lastYMin + 1]) && (Y >  fromTable->axisY[fromTable->lastYMax + 1]) )
    if ( (Y <  fromTable->axisY[y-1])                     && (Y >= fromTable->axisY[y]))
```
	
Uses 2 different bin tests:
```
	min >  Y >= max
	min >= Y >  max
```

Shouldn't the Y axis bin tests all be the same?

### PR DESCRIPTION
**Pull request by adbancroft**
This PR speeds up the 3d table bi-linear interpolation function: `get3DTableValue`.

With a 60-2 decoder, sweep from 1000 to 8000 at 300 revs/second, loops/sec improved by:

1. **Average 17%**
2. Minimum 6%
3. Maximum 31%

Speed up will depend on # of tables active. Numbers above based on 4 cylinder with individual fuel trims, VVT1 + VVT2, staged injection.

Also:

1. Saves 38 bytes of RAM.
2. Fixes #516

The code uses the same basic algorithm: caching + linear search from maximum values down. The speed up comes from:

1. Using 16-bit types instead of 32-bit. Especially in the fixed point math.
2. Micro-optimizations, such as incrementing/decrementing/offsetting pointers instead of array indexing, avoiding conditional tests where possible.
3. Using common/shared functions, especially when the code was subtly different to begin with.

Unit tests updated & all pass.

Log comparison using Ardustim: 60-2 decoder sweep from 1000 to 8000 at 300 revs/second (PR is the brighter line):
Missing Tooth 60-2 Sweep 1000-8000-300

### CODE REVIEW

**Comment by noisymime** [comment]
Hmm I'm actually seeing a fairly sharp drop in loops/s when testing this one. Setup is on a mega2560, but doing static RPM testing, so this result may come down to caching?

Test conditions are 3700rpm, 36-1, ASE off. Getting ~930 on current master, ~870 with this PR

**Comment by adbancroft** [comment]
Well that would be bad ;-)

I wasn't sure which 36-1 decoder you meant, so I ran a static test with the Mazda/Mitsu 4G63 - wheel 40 in Ardustim. I also turned off ASE & all extra tables (VVT, staged injection, fuel trims). Results are:

1. Average 4%
2. Min 0%
3. Max 7%

Not as good as the dynamic test, but that's probably a worst case improvement? (assuming it can be replicated)

4G63 at 3700

I also have direct timing tests of `get3DTableValue()` using a custom sketch with a variety of inputs (outside min/max, on bin edges etc.) - all show significant speedup.

Which Ardustim wheel are you using?

**Comment by adbancroft** [comment]
BTW, this is on a Mega 2560 with a Nano driving via Ardustim.

**Comment by adbancroft** [comment]
Second static test: 4G63 at 3700rpm with more tables in use - second fuel, second spark, seq fuel, stage inj & VVT1:

1. Average 15%
2. Min 7%
3. Max 21%


4G63 at 3700, Second Fuel, Second Spark, Seq Fuel, Stage Inj, VVT1

**Pull request merged**
