### PR TITLE
[DFCO] Add a minimum coolant

### PR DESCRIPTION
**Pull request by VitorBoss**
On pure ethanol and E85 the engine need a lot fuel to return from DFCO when cold.

### CODE REVIEW

**Comment by muuris** [comment]
And also higher cold start idle rpms require this to avoid humping.

**Comment by noisymime** [comment]
Thanks for another great submission Vitor.

Just reviewing, in `corrections.ino` should the temperature check include the offset:

Eg: `( currentStatus.coolant >= configPage2.dfcoMinCLT - CALIBRATION_TEMPERATURE_OFFSET)`

?

**Comment by VitorBoss** [comment]
Miss that, that offset should be on update.ino when I set the value? For °C and °F the offset changes right?

**Comment by muuris** [comment]
Internally in Speeduino data is always °C, the °F scaling is done in TS end (TS always sends the byte value which should be the same for °C/°F of same temperature)

**Comment by muuris** [comment]
I noticed dfcoMinCLT is defined as array (which it isn't) instead of scalar in .ini

**Comment by noisymime** [comment]
@VitorBoss You've got the calibration offset adding rather than subtracting. It should be something like:

`(currentStatus.coolant > (int)(configPage2.dfcoMinCLT - CALIBRATION_TEMPERATURE_OFFSET))`

**Comment by VitorBoss** [comment]
Fixed and squashed

**Pull request merged**
