### PR TITLE
Idle Up Target RPM Adder 

### PR DESCRIPTION
**Pull request by shiznit304**
This pull request adds a user configurable value to your target rpm for idle advance and PWM Closed loop, PWM Open+Closed Loop

Used for running A/C more smoothly

### CODE REVIEW

**Comment by choyr** [comment]
hey man, how's your idle up adder?

**Comment by shiznit304** [comment]
It works amazingly. This single thing made driving my Miata 10x better with A/C on. I have a video with this running in conjunction to another mod for closed loop idle up. https://www.youtube.com/watch?v=zR9Zl1x56Aw

**Comment by cgh459** [comment]
Will you see my comment on #580 and contact me somehow.  I wanted to know how you did some of your wiring so I can start testing some of these PRs.  Very intereated in figuring out the CEL switching.

**Comment by cgh459** [comment]
> Will you see my comment on #580 and contact me somehow. I wanted to know how you did some of your wiring so I can start testing some of these PRs. Very interested in figuring out the CEL switching.

That was absolutely what I needed. Thank you. Also another question. Do you need to physically open the ua4c ecu case and change any jumpers on the speeduino or is everything done on the adapter harness and in software?  Ive just heard about jumpers in the ua4c but never opened it

**Comment by shiznit304** [comment]
> 
> 
> > Will you see my comment on #580 and contact me somehow. I wanted to know how you did some of your wiring so I can start testing some of these PRs. Very interested in figuring out the CEL switching.
> 
> That was absolutely what I needed. Thank you. Also another question. Do you need to physically open the ua4c ecu case and change any jumpers on the speeduino or is everything done on the adapter harness and in software? Ive just heard about jumpers in the ua4c but never opened it

you don't need to open the UA4C ecu case. this is all done in the breakout board and software

**Comment by cgh459** [comment]
> > > Will you see my comment on #580 and contact me somehow. I wanted to know how you did some of your wiring so I can start testing some of these PRs. Very interested in figuring out the CEL switching.
> > 
> > 
> > That was absolutely what I needed. Thank you. Also another question. Do you need to physically open the ua4c ecu case and change any jumpers on the speeduino or is everything done on the adapter harness and in software? Ive just heard about jumpers in the ua4c but never opened it
> 
> you don't need to open the UA4C ecu case. this is all done in the breakout board and software

Sounds good.  Will solder in some jumper wires this evening. Thank you.

**Comment by cgh459** [comment]
It worked when i first hit my ac button now a8 seems like it always reads zero 

I set first rule as "aux in 1 == 0" and it turns on pin 25 regardless of the ac button being on or off

**Comment by cgh459** [comment]
When i hit my ac button with a8 set as idle up pin under idle up settings my idle goes up and down when i turn on or off ac like i expect it to function

But the programmable output for ac relay and condensor fan are always on, aux input 1 always == 0 no matter the state of the ac button

Under local auxillary input channel configuration the list begins at aux input 0

I set a8 as analog local for aux input 0 as shown in pictures

Then i set up my programmable outputs as shown in the pictures but under condition 1 i try aux in 1 == 0 and its always 0 no matter ac switch on or off so fan is always on 

Is that a bug where you define inputs starting at aux0 and then set up programmable outputs starting at aux1?  Meaning aux0 is really aux1?

**Comment by cgh459** [comment]
I applied the fix from #655 

Then there is a series of events i can do to make it work briefly

I go to Secondary Serial IO Interface
Enable Second Serial

Then go to local auxillary input configuration
change aux input 0 to external source
click burn and power cycle

then i go back to local auxillary input configuration
change aux input 0 to analog local a8
click burn but do not power cycle

during this period the input works as expected but as soon as i power cycle it is back to not working

**Comment by Afroboltski** [comment]
Did you see https://github.com/noisymime/speeduino/issues/654? I discovered a bug where, as you say, Aux. in 1 was actually aux. in 0. This fix is now in the master branch, I believe.

**Comment by github-account-0** [comment]
> Did you see #654? I discovered a bug where, as you say, Aux. in 1 was actually aux. in 0. This fix is now in the master branch, I believe.

I copied and pasted the ini file and it didnt work. Going to manually change 1 to 0 now

**Comment by shiznit304** [comment]
> 
> 
> When i hit my ac button with a8 set as idle up pin under idle up settings my idle goes up and down when i turn on or off ac like i expect it to function
> 
> But the programmable output for ac relay and condensor fan are always on, aux input 1 always == 0 no matter the state of the ac button
> 
> Under local auxillary input channel configuration the list begins at aux input 0
> 
> I set a8 as analog local for aux input 0 as shown in pictures
> 
> Then i set up my programmable outputs as shown in the pictures but under condition 1 i try aux in 1 == 0 and its always 0 no matter ac switch on or off so fan is always on
> 
> Is that a bug where you define inputs starting at aux0 and then set up programmable outputs starting at aux1? Meaning aux0 is really aux1?

@github-account-0 AuxInput0 (or 1 whatever it's called) should be around 1024 when the button is off, then around 100 when the button is on. If it's stuck at 0 then you're facing the aux in initialization bug. With all the values set to how they are in the post, it will work with your 96-97 PnP breakout board. Did you solder the jumpers and cut the traces?

**Comment by github-account-0** [comment]
> > When i hit my ac button with a8 set as idle up pin under idle up settings my idle goes up and down when i turn on or off ac like i expect it to function
> > But the programmable output for ac relay and condensor fan are always on, aux input 1 always == 0 no matter the state of the ac button
> > Under local auxillary input channel configuration the list begins at aux input 0
> > I set a8 as analog local for aux input 0 as shown in pictures
> > Then i set up my programmable outputs as shown in the pictures but under condition 1 i try aux in 1 == 0 and its always 0 no matter ac switch on or off so fan is always on
> > Is that a bug where you define inputs starting at aux0 and then set up programmable outputs starting at aux1? Meaning aux0 is really aux1?
> 
> @github-account-0 AuxInput0 (or 1 whatever it's called) should be around 1024 when the button is off, then around 100 when the button is on. If it's stuck at 0 then you're facing the aux in initialization bug. With all the values set to how they are in the post, it will work with your 96-97 PnP breakout board. Did you solder the jumpers and cut the traces? You shouldn't need secondary serial enabled.

The trace that is hard to see on bottom of picture that you have to cut is the one between two pins on the denso76 connector correct?  And not a pin on the denso76 to the diode correct?  It behaves exactly as expected when I follow the crazy sequence of setting and unsetting things, but i lose the working config on power cycle.  Its like some sort of initialization bug

I made my own bug report #673

**Pull request closed without merging**
