### PR TITLE
Add low/high battery voltage indicator

### PR DESCRIPTION
**Pull request by Corey-Harding**
This PR adds a user configurable Low/High Battery Voltage Indicator.

Battery Low/High Voltage settings are listed under "Settings", "Gauge Limits".

This enables the use of the battery icon in tuner studio for those using digital dashes.

I am going to use the battery icon now on my digital dash as a "dummy light" to indicate if my battery voltage is getting low or if the alternator is overcharging and if I see it lit then refer to either datalogs or the live battery voltage reading.

Made possible with a tip from @brunob45

Fulfills my "Feature Request" #822 

Ignore the random commits, my master branch deviates from master and I am making new branches from an old PR but I need to make a clean branch again for doing PRs, I also need to stop fetching upstream from web interface.  The only file changed is speeduino.ini as seen in the final and only relevant commit.

Tested key on/engine off(late night) and it works as expected when changing values.

### CODE REVIEW

**Comment by wilmardo** [comment]
About the commits, are you familiar with squashing? Here are two methods described (git reset --soft and an interactive rebase):
https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

This post describes this process in GitKraken:
https://www.gitkraken.com/learn/git/git-squash

Whatever git client you use there is always a way to squash commits.

Since git is decentralized you can try the squash on your local checkout without worrying, as long as you didn't push you can revert back with `git reset --hard origin/Add-HiLo-Battery-Voltage-Indicator` which sets your local checkout back to the state in Github (origin).

**Comment by Corey-Harding** [comment]
I had a long hiatus from github and used to use gitkraken almost exclusively and I also even used to host my own repositories but I don't spend much time on a real computer anymore nor do I self host anything.

I don't like the way the web interface squashes the commits when you pull upstream and it says that I am ahead of master.  But I use the web interface a lot to do just that because it is an easy way to stay up to date.  In fact I only recently downloaded the official github desktop application to resolve merge conflicts.

I am much more comfortable using a Debian based distribution as well but have recently been in a Windows environment due to needing to use certain applications and was getting tired of using virtual machines.  I just don't use a computer that much anymore at home and have a fairly busy lifestyle.  I know GitKraken and other clients are available as well for Windows but I don't remember ever using the official client so I tried it.

I just need to invest in a dedicated laptop again with modern specs and run an operating system and software I am comfortable with.

I appreciate the information though.

Only the last commit is relevant and all of the other commits bringing the branch even with master will be squashed if this gets merged.

**Comment by noisymime** [comment]
@wilmardo Squashing when submitting the PR itself isn't a huge issue as it will be squashed when it gets merged anyway. Having that history in the PR isn't typically an issue.

**Comment by Corey-Harding** [comment]
Thanks. I will still make a cleaner branch soon for future PRs

**Pull request merged**
