### PR TITLE
Vbatt reading overflow fixed. sensors.ino

### PR DESCRIPTION
**Pull request by TBAMax**
Prevent vbatt reading form going negative due to the vatVoltCorrect and overflowing the uint variable.
Variable changed to signed int  and added check to correct if gone negative.
Thought given that all filters using the temp variable shoud remain working.

Fixes issues that vbatt reading was erratic when negative vbatt correction was applied and battery not connected ( circuit on usb power).

### CODE REVIEW

**Comment by Autohome2** [comment]
It would be better to limit the corrected voltage to a minimum of zero volts rather than use a signed variable.
Battery voltage cannot go negative thus a corrected negative value from the calculation would be untrue.

**Comment by TBAMax** [comment]
> It would be better to explain that the corrected voltage could NOT have been allowed to go negative before checking which would have caused the overflow.And that a limit was introduced to fix the voltage to a minimum of zero volts as true battery voltage cannot really be negative

Yes, thanks. That is better explanation!

**Comment by VitorBoss** [comment]
I think is better to add a fail safe value, the voltage reading should never be < 4V and if this happens set a default 5V on the variable.

**Comment by noisymime** [comment]
I don't think there's a need for a default value here as this is a case that should never occur with an actual running engine. It's only to resolve the strangeness that could appear in TS when testing and don't have a 12v source connected.

I'm comfortable with this solution given the specific problem.

**Pull request merged**
