### PR TITLE
Unit test the schedule calculations

### PR DESCRIPTION
**Pull request by adbancroft**
Add unit tests for the scheduling calculations:

- calculateInjectorStartAngle
- calculateInjector1Timeout
- calculateInjectorNTimeout
- calculateIgnitionAngle1 - calculateIgnitionAngle8
- calculateIgnition1Timeout
- calculateIgnitionNTimeout

This required moving these functions out of speeduino.ino, but that's all that has been changed.

### CODE REVIEW

**Comment by adbancroft** [comment]
@noisymime This is the first in a series of scheduler focused PRs that will cumulatively save hundreds of bytes of RAM (along with small increases in speed & accuracy). To make that happen, there's a number of refactors that need to happen - these unit tests will give a high level of confidence during these changes.

Plus the PR is a Good Thing anyway :-)

**Comment by adbancroft** [comment]
Add some decoder unit tests.

**Comment by TBAMax** [comment]
@noisymime I take it that #804 is now considered obsolite. You obviously have some other plans going with @adbancroft ...

**Comment by henriquebelaz** [comment]
I believe there's a typo in "speeduino/schedule_calcs.inl". Master also won't compile without deleting the last line of "speeduino/schedule_calcs.h" (#include "schedule_calcs.inl").
I have little knowledge in coding but wanted to contribute anyways. Thanks

**Comment by adbancroft** [comment]
> @adbancroft I believe there's a typo in "speeduino/schedule_calcs.inl". Master also won't compile without deleting the last line of "speeduino/schedule_calcs.h" (#include "schedule_calcs.inl"). I have little knowledge in coding but wanted to contribute anyways. Thanks

You didn't mention it fails to compile in the **Arduino IDE** (obviously it compiles since the CI build works). I'll take a look.

**Pull request merged**
