### PR TITLE
Adjust semi-seq alternating injection pattern for 4 cylinders

### PR DESCRIPTION
**Pull request by brunob45**
As discussed in issue [#191](https://github.com/noisymime/speeduino/issues/191),
switching from Alternating to Simultaneous injection halves the pulse width.
I propose a simple solution for the 4-cylinder configuration.

Sequential injection, 1 squirt simultaneous and 2 squirts alternating all output the same pulse width.
2 squirts simultaneous and 4 alternating as well.

This should correlate with the expected behaviour.

To adapt this change to older tunes, one should only have to double the squirt number, if using alternating.

### CODE REVIEW

**Comment by noisymime** [comment]
Thanks for the PR, but there's some problems with how this will work. Semi-Seq setups can't run over 720 degrees because you can't be sure that you will have a trigger pattern that supports it. 

**Eg** Semi-Sequential works fine on a missing tooth arrangement that doesn't have a cam pulse. If you try to run the injection timing over 720 degrees though, the angle will never go above 360 and so you'll never see the 2nd lot of pulses you're adding

**Comment by brunob45** [comment]
Oh, I see...
Then, we would need to put injectors 1-4 and 2-3 on the same event (eg fuelSchedule1), then alternate between the two sets. Would that be an option?

**Comment by brunob45** [comment]
Alternating injection now works with 360 degree triggers and still behave as expected (for 4 cylinders).

**Comment by brunob45** [comment]
@noisymime I tested this fix with:
- Semi sequential injection, alternating and simultaneous, 
- Missing tooth at crank speed, without cam signal
- MAX_INJ_ANGLE = 720
- 4 strokes
And it worked.
Am I missing something?

**Comment by PSIG-dev** [comment]
From the thread linked in #191: **_"TL;DR — the calculated and actual fuel flow should remain the same when changing either the mode or the number of injections."_**  This is important, and why I am bumping it.  Also bumping #191.  Thanks for the efforts to resolve this!

**Comment by PSIG-dev** [comment]
This item (#211) has been deleted, not sure why.  Any updates?

**Comment by brunob45** [comment]
Just did some other tests with the code in this PR, got these numbers.
I also added some basic graphs showing the behaviour of the injectors for each configuration (not to scale and made on paint, excuse my lack of scope).
All the tests were at 150 rpm, 15% ve and basic distributor trigger.
v1 0
And, _I think_, this has not been merged into master because it will break the tunes of people running alternating, 2 squirts or more.

**Comment by PSIG-dev** [comment]
Cool. I am assuming this only represents timing, and the pulse widths in each are halved when they go to 2-per, or 25% each for 4, etc?  However for timing, my primary reaction is that the Alternating does not follow the sequence of 1-2-4 squirts, and instead shows settings of 2-per-cycle instead of 1, for the 1-squirt, like the other modes.  It may at-first seem minor, but was the primary error in function logic in "other" systems previously.  

I also don't think we should carry a basic error forward like this because it may 'break' older tunes — rather just tell users the ultra-simple **one-time** correction and we are past it.  Considering that users are having to deal with Req_fuel changes as it is now on every affected mode change, it would be a big improvement.  Awesome work and thanks for the visual.

**Comment by brunob45** [comment]
For the pulse width, correct. As the value on the gauge (minus 1ms deadtime) is 50% when going 2 squirts, and 25% with 4.
As of the alternating settings, we cannot set 1 squirt alternating, as it is hardcoded in Tunerstudio. Trying to do so will throw an error:

We could think of the alternating settings as the number of ignition _events_ (there are two that alternate eachother).
As of now, my changes only works on 4 and 6 cylinders. 2 and 3 are not affected by this bug, I think. So I'm only missing 5 and 8 cylinder engines.

**Comment by brunob45** [comment]
Just changed (yet again) the proposed solution.
Now, I have replaced the 'std_injection' panel in TunerStudio by custom fields, so there is no more, "number of squirts must be evenly divisible by the number of cylinders" errors : I replaced the "divider" field of the tune by a "nSquirts" field, which let us put whatever value we want.
Also, this fixes the issue discussed above.

**Pull request closed without merging**
