### PR TITLE
Free up unused function pins for programmable outputs

### PR DESCRIPTION
**Pull request by aaronjonesxyz**
Add function enabled checks to pinIsOutput macro for VVT, Fan and idle, to allow the pins to be used as programmable outputs.

### CODE REVIEW

**Comment by shiznit304** [comment]
Looks a lot like #549

**Comment by aaronjonesxyz** [comment]
> Looks a lot like #549

I forgot that existed, still isn't merged into master

**Comment by DeionSi** [comment]
It seems that the code has changed a bit here. Is it possible to get this synced with master?

**Comment by VitorBoss** [comment]
> It seems that the code has changed a bit here. Is it possible to get this synced with master?

Master already have something in place for that, I guess @noisymime forgot to close this PR

**Pull request closed without merging**
