### PR TITLE
Eclipsearduino fixes

### PR DESCRIPTION
**Pull request by mumme74**
These fixes makes it possible to use EclipseArduino while working on the code.
As far as I can see it has no negative effects on ordinary Arduino IDE

### CODE REVIEW

**Comment by noisymime** [comment]
Will test simetime over the next few days. Thanks!

**Comment by noisymime** [comment]
Possibly a silly question, but what's the purpose of the static casts to int within the trigger function of speeduino.ino? Can they be removed if curGap is made an unsigned int?

**Comment by mumme74** [comment]
Jepp they can go in that case, I didnt dare to change the datatype if there would be some case were values would be negative
Therefore I typecasted to silence a compiler warning.

**Comment by noisymime** [comment]
Updated to remove the cast and merged.

Thanks for the patch!

**Pull request merged**
