### PR TITLE
Basic sd-card logger.

### PR DESCRIPTION
**Pull request by Tjeerdie**
This is a basic sdcard logger, plus some other changes. This works on STM32 boards.
- Fixes for RTC on STM32. RTC now works and can be set from TS for STM32 with command pending boolean
- RTC is only started when selected to prevent lockup boards with no RTC crystal or battery. 
- Basic sd-card logger that can be enabled during boot/start-up. 
- Logging to CSV or some binary format
- Select-able log rate 1Hz, 4Hz, 10Hz, 30Hz
- Select-able CSV separation character 
- Builds for teensy35 are working. But logging does not work yet.(Thanks @pazi88 for testing) 
- There is some selection for file naming.
- A start for triggered logging is in here, just not yet ready.
- Tested in a 4 cylinder car and works at least until 5500RPM
- Test on the bench and still works until at-least 6000RPM. 

TODO
- Implement triggered logging
- Implement MLV file logging for megalog viewer. 
- Get files off the sdcard with msc/mass storage for STM32 (For teensy it is unclear how to solve this)

Nice to Have
- Triggered log to SPI eeprom
- Be able to select what needs logging and what not from Tuner Studio.

---------  List of commits ------------------
Some more general clean-up
Add more explanation
some clean-up of dublicate code
clean-up of duplicate code
fixing naming of file.
General clean-up
General clean-up
fix boost dutycyle in log
Fix for setting rtc with pending command bool.
Small rtc fixes, and general sdcard clean-up
Changed the command 'w' for setting RTC time back to original
RTC fixes and changes
Some RTC clean-up
Add nSquirt for correct duty cycle calculations
Adding floats to logger
Setting correct names so megalogviewer understands
Adding Time for mega log viewer
Add Dutycyle calculations for logging
Prevent freeram overflowing on STM32
Bug fix indicators
General comments update
Remove debug statements
Adding teensy support for sdcard logging (untested)
Tevert changes to platformio.ini
Working async logger STM32
Hopefully small bugfix
Bug fix for arduino IDE. (thanks @pazi88)
Fix for building teensy boards.
Add some comments to the sd card logging
General clean-up and improvements of logger
Exclude all other platforms from compiling the STM32 sd card liberary
Adding binary logging
Some more cleanup on sdcard logging
Some more improvements and configuration settings
Initial work updating ini and globals.h
Kind of working sdcard logger
Add forgotten function
Add new type of field generation for csv
Clean-up debug statements
Added changes to speeduino files to add sdcard logging
Add necessary new files for sdcard logging STM32 in library folder.

### CODE REVIEW

**Comment by Tjeerdie** [comment]
So far logged 3.6GB of data on a running car.

**Comment by pazi88** [comment]
Great to know! I will be definitely running this once my car is back on road.

**Comment by pkagiantas** [comment]
@Tjeerdie tried it on a fresh black stm F4VE but it still does the same like i posted on your git hub 
it starts to log fin but runs for 20-30 seconds and then it gives an sd er 

i can upload log and tune if you like to check it 

i will give it a try with a new sd next week just to rule out the sd card

**Comment by Tjeerdie** [comment]
> @Tjeerdie tried it on a fresh black stm F4VE but it still does the same like i posted on your git hub
> it starts to log fin but runs for 20-30 seconds and then it gives an sd er
> 
> i can upload log and tune if you like to check it
> 
> i will give it a try with a new sd next week just to rule out the sd card

hmm ok, at the moment i am tracing a ignition bug that potentially has blown my head gasket. That is first priority for me. 

I assume you have selected the stm32F407 board in tuner studio (just to rule out any pins conflicts). And started with a fresh initial tune with the bare minimum to get something logging? (no programmable outputs/inputs, no CAN, etc).

**Comment by pkagiantas** [comment]
> 
> 
> > @Tjeerdie tried it on a fresh black stm F4VE but it still does the same like i posted on your git hub
> > it starts to log fin but runs for 20-30 seconds and then it gives an sd er
> > i can upload log and tune if you like to check it
> > i will give it a try with a new sd next week just to rule out the sd card
> 
> hmm ok, at the moment i am tracing a ignition bug that potentially has blown my head gasket. That is first priority for me.
> 
> I assume you have selected the stm32F407 board in tuner studio (just to rule out any pins conflicts). And started with a fresh initial tune with the bare minimum to get something logging? (no programmable outputs/inputs, no CAN, etc).

stm32F407  on board layout correct 
here is the tune if you like to see it https://we.tl/t-2GJrOjZrGc

**Comment by Tjeerdie** [comment]
Ow, the discussion below #534 is more relevant to this PR actually.

**Pull request closed without merging**
