### PR TITLE
Code reliability improvements.

### PR DESCRIPTION
**Pull request by TBAMax**
Started work on determining one by one what variables are not really suppose to be global. I determine variable to be local variable when it is used only in the scope of one function (no cross usage).

### CODE REVIEW

**Comment by muuris** [comment]
But doesn't this just end up with a lot more unnecessarily duplicated code without any real benefits?

**Comment by TBAMax** [comment]
@muuris, it end up with slightly more lines yes. But at the same time makes code much more understandable. Also makes for less  prone to coding errors because in case of variable is accidentally attempted to be used out of the scope it throws error.

**Comment by TBAMax** [comment]
I have been gradually adding some commits to this PR. But in this PR will only be work on decoders.ino and decoders.h

**Comment by TBAMax** [comment]
Seems this is inessential, so close this now instead of maintaining.

**Pull request closed without merging**
