### PR TITLE
PWM fan control

### PR DESCRIPTION
**Pull request by pazi88**
This PR adds PWM fan control for Teensy and STM32. The Arduino MEGA lacks timers to do this, so if user tries to select PWM fan mode with that MCU, Tuner Studio gives warning that it isn't available and PWM Fan related options are grayed out. Tested to work on STM32, but don't own Teensy, so for that I only tested that this compiles.

### CODE REVIEW

**Comment by VitorBoss** [comment]
Nice work, you know how to squash those commits to a single one? I think it's a lot of them

**Comment by pazi88** [comment]
Actually no idea how to do that. There is multiple commits, because I work on multiple PCs when ever I have time, so I have to commit the changes when ever I swap PC, even thought the coding wouldn't be done yet/tested.

**Comment by ChadBailey** [comment]
random person just happen to be lurking... give interactive rebase a try... something like `git rebase -i HEAD~20` or however many commits you wanna go back. just keep in mind the squashed commit gets put into the newer commit, so you can't squash the most recent one

**Comment by VitorBoss** [comment]
When there is a big number of commits and some in between is from master I do thi:

- > Backup the modified files, or the speeduino folder and ini.
- > Open main speeduino folder, the one with readme file. 
- > Right click and select `open bash/prompt`
- > enter the command `git rebase -i ac6f1d1b255b1589fda397a5ab813a514d823435`
- > A editor will open with the commits, something like `pick 460d772 modified speeduino ini`
- > Replace every **pick** word with a **d**, that will delete the commit but don't worry 
- > Save the file and close it
- > enter the command `git rebase upstream/master`, that will pick the recent changes
- > Now you can restore the backup files, it will appear to you like your first commit on that branch
- > After name the commit don't push the changes, you need to use the command `git push --force-with-lease origin`

Is easier than it looks. After that your PR will have just one commit.

**Comment by pazi88** [comment]
> When there is a big number of commits and some in between is from master I do thi:
> 
> * > Backup the modified files, or the speeduino folder and ini.
> * > Open main speeduino folder, the one with readme file.
> * > Right click and select `open bash/prompt`
> * > enter the command `git rebase -i ac6f1d1b255b1589fda397a5ab813a514d823435`
> * > A editor will open with the commits, something like `pick 460d772 modified speeduino ini`
> * > Replace every **pick** word with a **d**, that will delete the commit but don't worry
> * > Save the file and close it
> * > enter the command `git rebase upstream/master`, that will pick the recent changes
> * > Now you can restore the backup files, it will appear to you like your first commit on that branch
> * > After name the commit don't push the changes, you need to use the command `git push --force-with-lease origin`
> 
> Is easier than it looks. After that your PR will have just one commit.

umm not sure if I'm doing this correctly. But If I us d to delete all lines and after saving and closing (:wq! -command) it says nothing to do.

**Comment by pazi88** [comment]
WTF. now it's totally messed. I give up.

**Pull request closed without merging**
