### PR TITLE
Fix Jeep2000 decoder

### PR DESCRIPTION
**Pull request by jonbills**
getCrankAngle_Jeep2000() sets crankangle = 146 if toothcurrentcount = 0, because last tooth was cam tooth  which is 146 ATDC, however, all the timing and angle calculations are not done on the cam tooth read, so crankangle should be set to 114 for previous crank tooth.
problem was found by @jaky 47 on Slack, and fix tested and confirmed by him.

### CODE REVIEW

**Comment by jonbills** [comment]
ooh,  should this have been a PR against the 202207-fixes branch instead?

**Comment by jonbills** [comment]
Problem description in #897

**Comment by JaredSellers4** [comment]
@jonbills, the crank tooth degrees in this decoder are rising edge so should it actually be 114 degrees?

**Comment by jonbills** [comment]
It certainly fixed the problem of the duplicate and very early signal. I think youre right that 114 would be more correct. I'll update to that.
Most of the comment is the original authors, I just appended a note on the correction.

**Comment by jonbills** [comment]
redoing as two PRs - one an LTS 'fix' for the original logic error , the other a non LTS 'improvements' (noise filtering)

**Pull request closed without merging**
