### PR TITLE
Map Threshold for DFCO

### PR DESCRIPTION
**Pull request by 155ac**
*Adds a MAP threshold option for DFCO, This will make the DFCO code to work like the ms2, It will only trigger the DFCO when both MAP and TPS are below the threshold

*Adds minimum value of 0.5% for TPS this fix a problem when the values is set to 0% the DFCO is not triggering because the TPS never gets below 0%

*Adds default values for DFCO in TS

*Change DCFO settings locations and change some names for better understanding

new dfco

### CODE REVIEW

**Comment by Nocnafuria22** [comment]
Great feature but don't forget to add hysteresis because the map value can oscillate during DFCO.

**Comment by 155ac** [comment]
> Great feature but don't forget to add hysteresis because the map value can oscillate during DFCO.

there is no need for hysteresis because the speeduino it self have a option to remove oscillations from the map.

**Comment by Nocnafuria22** [comment]
> > Great feature but don't forget to add hysteresis because the map value can oscillate during DFCO.
> 
> there is no need for hysteresis because the speeduino it self have a option to remove oscillations from the map.

Not with instantaneous map sample method. Even with event average it can oscilate 1-2 kpa per 0.5 sec.

**Comment by noisymime** [comment]
1 concern I have with this is what happens if someone doesn't have a MAP sensor connected? The same can probably be said for TPS, but that is more unusual than no MAP sensor. 

Is it worth adding a separate option to enable this?

**Comment by Nocnafuria22** [comment]
``
> 
> Is it worth adding a separate option to enable this?

In my case it would be helpfully.

**Pull request closed without merging**
