### PR TITLE
Main relay support

### PR DESCRIPTION
**Pull request by ByteVenom**
Adds the ability for the Speeduino to automatically turn on the main relay upon startup.

### CODE REVIEW

**Comment by ByteVenom** [comment]
Why is it failing the Azure check?

**Comment by ByteVenom** [comment]
Any issues why this can't be merged?

**Comment by WindBasevi** [comment]
It can! Its up to you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ByteVenom** [comment]
> It can! Its up to you Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10


Not sure what you mean.

**Pull request closed without merging**
