### PR TITLE
[PID] Increase parameters and output resolution

### PR DESCRIPTION
**Pull request by VitorBoss**
Parameters are 0.03125% for Kp and Ki, 0.00981% for Kd. Increased output 4 times to give enough room for stepper.

PID now ignore compute if input is zero to avoid overshoot, Ki and Kd part as well.

Added idlePID.Initialize() to crank part to start PID from a working condition.

Show idleLoad when cranking.

### CODE REVIEW

**Comment by VitorBoss** [comment]
This is a RC filter(18K,10uF) using 0.6, 3.6 and 0.02 for PID. As you can see, the resolution changes are working as intended.

comp

**Comment by maclof** [comment]
@VitorBoss this change works really well, thanks! :)

**Comment by adbancroft** [comment]
> This is a RC filter(18K,10uF) using 0.6, 3.6 and 0.02 for PID. As you can see, the resolution changes are working as intended.
> 
> comp

This would make a really good test. Do you still have the numbers that make this graph?

**Comment by VitorBoss** [comment]
@adbancroft The numbers are there, P is 0.6, I is 3.6 and D is 0.02.
The setpoint seems like 155, just controlling a PWM signal with a 18K resistor to a 10uF capacitor on the analog input

**Comment by adbancroft** [comment]
I was hoping for the timestep, input & output in tabular format. E.g.

|Time|Input|output|
|-----|-----|------|
|1|15|39|
|2|46|30|
etc.

(made up numbers....)

**Pull request merged**
