### PR TITLE
Change Aux in from 1-16 to 0-15 under programmable outputs

### PR DESCRIPTION
**Pull request by Corey-Harding**
This is the new #676 changing the branch name i had to make a new PR

Changes "Aux in" 1-16 to 0-15 under "programmable outputs" menu to match the pin configuration page found under "local auxillary input channel configuration" menu as suggested by @afroboltski

### CODE REVIEW

**Comment by github-account-0** [comment]
This PR has worked good on my setup for a few months using it to drive the ac condensor, fan, and cel

**Comment by Corey-Harding** [comment]
@pazi88 @Afroboltski @shiznit304 
Changing the branch name closed my old PR this is the new PR for Change Aux in from 1-16 to 0-15 under programmable outputs

**Comment by noisymime** [comment]
Just to confirm, does this resolve #673 ?

**Comment by Corey-Harding** [comment]
Yes although to do exactly what I wanted to I also had to also do this

https://github.com/Corey-Harding/speeduino/commit/e11864160506a487f099fc83d86c1fd4795423fd

And disable the pinisinput check

**Comment by Corey-Harding** [comment]
Well in case you dont read comment edits and just use emails then I guess technically no this PR doesnt fix that issue entirely because one of the pinisoutput checks is causing me an issue for my use case but it fixes the ordering issue.

Im using prog outouts pin A8 to control my ac fan and the same pin for idle up so it fails unless i disable the check on that pin.

**Comment by shiznit304** [comment]
I had to revert this PR to allow my Local Input Auxiliary Channel Configuration to work again. I believe the pins weren't initializing or something. All the pin values were 0

**Comment by pazi88** [comment]
Are you using digital inputs? This PR should only affect those (fix bug that has been there for lomg time). Also the programmable output related naming is the only other thing changed.

**Comment by shiznit304** [comment]
Yes I am using digital inputs. Although my firmware has several other pr.
I’d have to test with master alone to verify.

**Comment by Corey-Harding** [comment]
You need to choose the new aux number that matches? Before your aux input
was 1 now it is 0, 2 is now 1, etc.

**Comment by shiznit304** [comment]
Yes I tried adjusting my programmable outputs but that didn't work. All my
digital pins (I didn’t check if it affected analog) were stuck at 0.

**Comment by Corey-Harding** [comment]
I was just going off what others had said they needed to do with the 63+1. I only use analog inputs. But the labeling did need to be changed to match for sure.

You changed the aux in 1 to aux in 0 though on the programmable outputs menu in far left side of tuner studio where you set up the conditions to match labeling?

**Comment by Corey-Harding** [comment]
It matches the settings now in speeduino ino you can try 127+1 though.

I also think pina might need to be changed to 63 from 127.

**Comment by shiznit304** [comment]
Yes the labeling matched, aux 0. My condition was checking if the aux input
is a 1 or 0. I also have hard coded some other things outside of
programmable outputs that check the pin status. But the pin never
initialized and stayed stuck at 0.

**Comment by Corey-Harding** [comment]
I have to do this with my personal vehicle
https://github.com/Corey-Harding/speeduino/commit/e11864160506a487f099fc83d86c1fd4795423fd

**Comment by shiznit304** [comment]
does #803 the issue caused by this PR?

**Comment by Corey-Harding** [comment]
It does not. I think the issue you are facing is the same issue I had after this PR.

#398

**Pull request merged**
