### PR TITLE
Boost by gear (Open loop)

### PR DESCRIPTION
**Pull request by DylanRooijakkers**
This PR expands the functionality of boost by gear to open loop boost control. The constant limit in open loop sets a max duty cycle percentage.

### CODE REVIEW

**Comment by shiznit304** [comment]
@jackscr12

**Comment by jackscr12** [comment]
Been away for a while ,but now I am finally home  and will test it as soon as possible

**Comment by jackscr12** [comment]
OK finally tested this and everything works  fine, both multiplied and constant limit work as expected. Great job!!

**Comment by DylanRooijakkers** [comment]
@jackscr12  That's great to hear!

**Pull request merged**
