### PR TITLE
Added Spark EFI V1.x board and Added selectable pin function for idle air valve.

### PR DESCRIPTION
**Pull request by emretunali**
Board ID=35 Spark EFI V1.x

### CODE REVIEW

**Comment by noisymime** [comment]
Hi, what license are your boards released under? 

The policy around board mappings is that they will be included if under an open license with a published link to the design files.

**Comment by emretunali** [comment]
Hi Josh, today I will upload and link to my github. V1.0 and V1.1

**Comment by emretunali** [comment]
https://github.com/emretunali/Spark-EFI-V1.1-Speeduino-Compatible

**Comment by kovama1** [comment]
> https://github.com/emretunali/Spark-EFI-V1.1-Speeduino-Compatible

Do you have also gerber files and others so I can build one myself? Looks cool tho :)

**Comment by emretunali** [comment]
> > https://github.com/emretunali/Spark-EFI-V1.1-Speeduino-Compatible
> 
> Do you have also gerber files and others so I can build one myself? Looks cool tho :)

Yes. I have now uploaded.

**Comment by emretunali** [comment]
@noisymime Is there anything else I need to do ?

**Pull request closed without merging**
