### PR TITLE
Performance and economic fields of tunerstudio

### PR DESCRIPTION
**Pull request by nuosu**
Added custom channels to use the performance and economic fields of tunerstudio, becoming accurate and usable

### CODE REVIEW

**Comment by noisymime** [comment]
Hi. Not quite sure what you're trying to achieve with this change? There is only a single line changed in the ini file and that doesn't look like it enables any of the mentioned fields.

**Comment by nuosu** [comment]
i have tested  that function in tunerstudio .  but get wrong data. The
vehicle speed is too much higer than speeduino .after that. I tried to add
a custom output channel in accordance with the requirements of tunerstudio
. The problem is solved

Josh Stewart ***@***.***> 于 2021年8月2日周一 下午3:11写道：

**Comment by noisymime** [comment]
Closing as I can't see what the actual changes are here. Please open a new PR if needed

**Comment by pazi88** [comment]
I have the economy fields currently baked into speeduino.ini. I will make PR once testing is complete.

**Pull request closed without merging**
