### PR TITLE
refactor: parameterize the MISRA checking script

### LINKED ISSUE #505: MISRA script is difficult to run
The MISRA script (check_misra.sh) has hardcoded paths, assumes it's being run from a root outside the code tree and drops files into the code tree.

Cleaning this up will make it easier to run & for contributors to follow the contribution recommendations

### PR DESCRIPTION
**Pull request by adbancroft**
The script contained hardcoded paths, which made it difficult to use as part of the development workflow.

Fixes #505

### CODE REVIEW

**Comment by noisymime** [comment]
Looking good! The only other thing you'll need to lookout is updating the `azure-pipelines.yml` script as it is what runs the automated MISRA scanning.  I'd like to get everything in the same PR if possible to avoid any breakage

**Comment by adbancroft** [comment]
> 
> 
> Looking good! The only other thing you'll need to lookout is updating the `azure-pipelines.yml` script as it is what runs the automated MISRA scanning. I'd like to get everything in the same PR if possible to avoid any breakage

All part of the plan.....

**Comment by adbancroft** [comment]
Should be good to go: one configurable MISRA script for both devs & the CI pipeline,.

**Comment by noisymime** [comment]
Awesome!

I'll pull it in and we'll see how the CI/CD testing goes :)

**Pull request merged**
